# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarvelMVCExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelMVCExample
  pod 'Alamofire', '~> 4.0.0'
  pod 'Kingfisher', '~> 5.3'
  pod 'SwiftHash', '~> 2.0'
end
